#! /bin/sh
#
# skeleton	example file to build /etc/init.d/ scripts.
#		This file should be used to construct scripts for /etc/init.d.
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#               Further changes by Javier Fernandez-Sanguino <jfs@debian.org>
#
# Version:	@(#)skeleton  1.9  26-Feb-2001  miquels@cistron.nl
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/tablesnap
NAME=tablesnap
DESC=tablesnap

test -x $DAEMON || exit 0

LOGDIR=/var/log/tablesnap
PIDFILE=/var/run/$NAME.pid
DODTIME=1                   # Time to wait for the server to die, in seconds
                            # If this value is set too low you might not
                            # let some servers to die gracefully and
                            # 'restart' will not work

# Include defaults if available
if [ -f /etc/default/tablesnap ] ; then
    . /etc/default/tablesnap
fi

set -e

running()
{
    daemon --running --name $NAME
    return $?
}

case "$1" in
  start)
        echo -n "Starting $DESC: "
        daemon --name=$NAME --unsafe --pidfile=$PIDFILE --output=$LOGDIR/$NAME.log -- $DAEMON $DAEMON_OPTS
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        daemon --name=$NAME --stop
        echo "$NAME."
        ;;
  restart)
    echo -n "Restarting $DESC: "
    daemon --name=$NAME --restart
    echo "$NAME."
    ;;
  status)
    if running; then
        echo "running"
        exit 0
    else
        echo "stopped"
        exit 1
    fi
    ;;
  *)
    N=/etc/init.d/$NAME
    # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
    echo "Usage: $N {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
